import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Payment Failed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main}`}>
       <p>Payment failed.<br/>Description: {decodeURI(router.query.error)}</p>
      </div>
    </>
  )
}
