import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import axios from 'axios'

export default function Home() {

  const pay = async () => {
    const res = await axios.get('/api/order')
    console.log(res.data)
    const rzp = new Razorpay({
      key: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
      amount: res.data.amount,
      currency: res.data.currency,
      name: process.env.NEXT_PUBLIC_ACCOUNT_NAME,
      order_id: res.data.id,
      redirect: true,
      callback_url: 'http://localhost:3000/api/payment'
    })
    rzp.open();
  }

  return (
    <>
      <Head>
        <title>Razorpay Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </Head>
      <div className={`${styles.main}`}>
        <button className={`${styles.button}`} onClick={pay}>Proceed to pay</button>
      </div>
    </>
  )
}
